### PR TITLE
Run vue3-recommended linting

### LINKED ISSUE #45: Consider enabling stricter JS linting for the webapp
Currently the vue linting is set to "essentials". It would be good to enable stricter linting with more automatic  formatting by using "strongly-recommended" or "recommended." See: https://eslint.vuejs.org/rules/

These will help with readability and reduce the need for style decisions by enforcing autoformatting the order of tags, methods, etc. However, it will take some initial investment to fix the many existing errors!

The setting in question is: https://github.com/the-grey-group/datalabvue/blob/331e936a37edcac207d4bdbc4d7fa7db23dcdbae/webapp/.eslintrc.js#L6

`plugin:vue/vue3-essential` can be changed to `plugin:vue/vue3-strongly-recommended` or `plugin:vue/vue3-recommended`

### PR DESCRIPTION
**Pull request by jdbocarsly**
Closes #45.

### CODE REVIEW

**Comment by BenjaminCharmes** [comment]
I rebase main to retrieve the docker-compose changes.

For the moment I've deactivated 4 rules:

- "vue/prop-name-casing"
- "vue/require-default-prop"
- "vue/require-prop-types"
- "vue/v-on-event-hyphenation" 

And dealt with the other problems case-by-case. I'm going to spend a little more time on it to make sure it all works. If you'd like me to reactivate any of the rules and fix the problems so that the errors don't trigger again, let me know.

**Comment by BenjaminCharmes** [comment]
pre-commit.ci autofix

**Review by ml-evs — DISMISSED** [review]

**Review by ml-evs — DISMISSED** [review]
Thanks @BenjaminCharmes (and to a much lesser extent @jdbocarsly :P)

**Review by ml-evs — APPROVED** [review]

**Comment by ml-evs** [comment]
PR is failing for some weird transient mypy reason, lets not hold this up and hope that we can fix it elsewhere

**Pull request merged**
