### PR TITLE
Add 'optical' cellFormat

### LINKED ISSUE #787: Missing "optical" cell formats
Requested by Veronika: 

- We should add "Optical" to the available cell formats

### PR DESCRIPTION
**Pull request by BenjaminCharmes**
Close #787 

Added 'optical' to cell formats

### CODE REVIEW

**Comment by BenjaminCharmes** [comment]
pre-commit.ci autofix

**Comment by BenjaminCharmes** [comment]
pre-commit.ci autofix

**Review by jdbocarsly — APPROVED** [review]

**Comment by ml-evs** [comment]
pre-commit.ci run

**Review by ml-evs — DISMISSED** [review]
Pending pre-commit run, this lgtm, is it ready to merge @BenjaminCharmes?

**Comment by ml-evs** [comment]
Ah the problem is that pre-commit CI cannot run the schema linter (I think). I'll manually run this.

**Comment by BenjaminCharmes** [comment]
> Pending pre-commit run, this lgtm, is it ready to merge @BenjaminCharmes?

Yes !

**Review by ml-evs — APPROVED** [review]

**Pull request merged**
